In [1]:
import pandas as pd

In [2]:
# check version
pd.__version__

'2.2.2'

In [3]:
# 1.Create Dataframe
df = pd.DataFrame([11,12,13,14,15,16,17,18],columns = ['col_Name'])
print(df)

   col_Name
0        11
1        12
2        13
3        14
4        15
5        16
6        17
7        18

In [4]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [5]:
data = {
    'name':['madhav','vansh','lalit','Anu'],
    'Age':[16,23,45,33],
    'Salary':[12000,23000,22000,23000]
    
}

In [6]:
df = pd.DataFrame(data)
print(df)

     name  Age  Salary
0  madhav   16   12000
1   vansh   23   23000
2   lalit   45   22000
3     Anu   33   23000

In [7]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [8]:
# 2. Basic DataFrame Understanding

In [9]:
df.head(2) #top rows

     name  Age  Salary
0  madhav   16   12000
1   vansh   23   23000

In [10]:
df.tail(2) #Last rows

    name  Age  Salary
2  lalit   45   22000
3    Anu   33   23000

In [11]:
df.shape  #rows&columns

(4, 3)

In [12]:
df.columns

Index(['name', 'Age', 'Salary'], dtype='object')

In [13]:
df.rename(columns={'Salary':'Monthly_salary'})

     name  Age  Monthly_salary
0  madhav   16           12000
1   vansh   23           23000
2   lalit   45           22000
3     Anu   33           23000

In [14]:
df

     name  Age  Salary
0  madhav   16   12000
1   vansh   23   23000
2   lalit   45   22000
3     Anu   33   23000

In [15]:
df.rename(columns={'Salary':'Monthly_salary'},inplace=True)

In [16]:
df

     name  Age  Monthly_salary
0  madhav   16           12000
1   vansh   23           23000
2   lalit   45           22000
3     Anu   33           23000

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            4 non-null      object
 1   Age             4 non-null      int64
 2   Monthly_salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [18]:
df.describe()

             Age  Monthly_salary
count   4.000000        4.000000
mean   29.250000    20000.000000
std    12.606215     5354.126135
min    16.000000    12000.000000
25%    21.250000    19500.000000
50%    28.000000    22500.000000
75%    36.000000    23000.000000
max    45.000000    23000.000000

In [19]:
# 3. Save and Load data from csv

In [20]:
df.to_csv('test_data.csv',index=False) #export data frame

In [21]:
load_df=pd.read_csv('test_data.csv') #import dataframe
load_df

     name  Age  Monthly_salary
0  madhav   16           12000
1   vansh   23           23000
2   lalit   45           22000
3     Anu   33           23000

In [22]:
# 4. Rows &columns - Selection
df[['name']] # Single column

     name
0  madhav
1   vansh
2   lalit
3     Anu

In [23]:
df[['name','Monthly_salary']]

     name  Monthly_salary
0  madhav           12000
1   vansh           23000
2   lalit           22000
3     Anu           23000

In [24]:
# Select Rows
# loc - label based index
df.loc[df.name=='madhav']

     name  Age  Monthly_salary
0  madhav   16           12000

In [25]:
df.loc[(df.name=='madhav')&(df.Monthly_salary>=10000)]

     name  Age  Monthly_salary
0  madhav   16           12000

In [26]:
df.loc[df.Age==23]

    name  Age  Monthly_salary
1  vansh   23           23000

In [27]:
df.loc[0:2]

     name  Age  Monthly_salary
0  madhav   16           12000
1   vansh   23           23000
2   lalit   45           22000

In [28]:
# iloc- index-value based
df.iloc[0]

name              madhav
Age                   16
Monthly_salary     12000
Name: 0, dtype: object

In [29]:
df.iloc[0:2]

     name  Age  Monthly_salary
0  madhav   16           12000
1   vansh   23           23000

In [30]:
# Filter Dataframe

In [31]:
df

     name  Age  Monthly_salary
0  madhav   16           12000
1   vansh   23           23000
2   lalit   45           22000
3     Anu   33           23000

In [32]:
df['Age'] > 20

0    False
1     True
2     True
3     True
Name: Age, dtype: bool

In [33]:
df[df['Age'] > 20]

    name  Age  Monthly_salary
1  vansh   23           23000
2  lalit   45           22000
3    Anu   33           23000

In [34]:
df[(df['Age'] > 20)&(df['Monthly_salary']>=20000)]

    name  Age  Monthly_salary
1  vansh   23           23000
2  lalit   45           22000
3    Anu   33           23000

In [35]:
df.where(df['Age']>20)

    name   Age  Monthly_salary
0    NaN   NaN             NaN
1  vansh  23.0         23000.0
2  lalit  45.0         22000.0
3    Anu  33.0         23000.0

In [36]:
df.where(df['Age']>20,other = 'Not Eligible')

           name           Age Monthly_salary
0  Not Eligible  Not Eligible   Not Eligible
1         vansh            23          23000
2         lalit            45          22000
3           Anu            33          23000

In [37]:
# Rows & Columns - Operations(Add,Update,Delete)
df

     name  Age  Monthly_salary
0  madhav   16           12000
1   vansh   23           23000
2   lalit   45           22000
3     Anu   33           23000

In [38]:
# Add new column
df['team']=['CEO','Hr','CTO','DA']
df

     name  Age  Monthly_salary team
0  madhav   16           12000  CEO
1   vansh   23           23000   Hr
2   lalit   45           22000  CTO
3     Anu   33           23000   DA

In [39]:
df['Bonus'] = df['Monthly_salary']* 0.2
df

     name  Age  Monthly_salary team   Bonus
0  madhav   16           12000  CEO  2400.0
1   vansh   23           23000   Hr  4600.0
2   lalit   45           22000  CTO  4400.0
3     Anu   33           23000   DA  4600.0

In [40]:
# Add new row
df.loc[len(df)]=['Anya',23,23000,'hr',4600]
df

     name  Age  Monthly_salary team   Bonus
0  madhav   16           12000  CEO  2400.0
1   vansh   23           23000   Hr  4600.0
2   lalit   45           22000  CTO  4400.0
3     Anu   33           23000   DA  4600.0
4    Anya   23           23000   hr  4600.0

In [41]:
len(df)

5

In [42]:
# Update Value -Using index value
df.loc[0,'Age']=19
df

     name  Age  Monthly_salary team   Bonus
0  madhav   19           12000  CEO  2400.0
1   vansh   23           23000   Hr  4600.0
2   lalit   45           22000  CTO  4400.0
3     Anu   33           23000   DA  4600.0
4    Anya   23           23000   hr  4600.0

In [43]:
# Update Value -Using index value
df.loc[df.name=='madhav','Monthly_salary'] = 35000
df

     name  Age  Monthly_salary team   Bonus
0  madhav   19           35000  CEO  2400.0
1   vansh   23           23000   Hr  4600.0
2   lalit   45           22000  CTO  4400.0
3     Anu   33           23000   DA  4600.0
4    Anya   23           23000   hr  4600.0

In [44]:
#delete Value - rows & column
df = df.drop(df[df.name=='Anya'].index) # drop row ,axis=0
df

     name  Age  Monthly_salary team   Bonus
0  madhav   19           35000  CEO  2400.0
1   vansh   23           23000   Hr  4600.0
2   lalit   45           22000  CTO  4400.0
3     Anu   33           23000   DA  4600.0

In [45]:
df.drop('Bonus',axis=1,inplace=True) #drop column

In [46]:
df

     name  Age  Monthly_salary team
0  madhav   19           35000  CEO
1   vansh   23           23000   Hr
2   lalit   45           22000  CTO
3     Anu   33           23000   DA

In [47]:
# multiple column delete
# df.drop(['Bonus','team'])

In [48]:
df.drop(1,axis=0) # index name

     name  Age  Monthly_salary team
0  madhav   19           35000  CEO
2   lalit   45           22000  CTO
3     Anu   33           23000   DA

In [49]:
df

     name  Age  Monthly_salary team
0  madhav   19           35000  CEO
1   vansh   23           23000   Hr
2   lalit   45           22000  CTO
3     Anu   33           23000   DA

In [50]:
# sort value
df.sort_values('Monthly_salary')

     name  Age  Monthly_salary team
2   lalit   45           22000  CTO
1   vansh   23           23000   Hr
3     Anu   33           23000   DA
0  madhav   19           35000  CEO

In [51]:
df.sort_values('Monthly_salary',ascending=False)

     name  Age  Monthly_salary team
0  madhav   19           35000  CEO
1   vansh   23           23000   Hr
3     Anu   33           23000   DA
2   lalit   45           22000  CTO

In [52]:
df['DOJ'] = ['2020/01/02','2023/01/01','2025/02/01','2026/11/11']
df

     name  Age  Monthly_salary team         DOJ
0  madhav   19           35000  CEO  2020/01/02
1   vansh   23           23000   Hr  2023/01/01
2   lalit   45           22000  CTO  2025/02/01
3     Anu   33           23000   DA  2026/11/11

In [53]:
df['DOJ'].dtype

dtype('O')

In [54]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [55]:
df['DOJ'].dtype

dtype('<M8[ns]')

In [56]:
df1 = df

In [57]:
df1

     name  Age  Monthly_salary team        DOJ
0  madhav   19           35000  CEO 2020-01-02
1   vansh   23           23000   Hr 2023-01-01
2   lalit   45           22000  CTO 2025-02-01
3     Anu   33           23000   DA 2026-11-11

In [58]:
df1['DOJ2'] = ['2020/01/02','2023/01/01','2025/02/01','2026/11/11']
df1

     name  Age  Monthly_salary team        DOJ        DOJ2
0  madhav   19           35000  CEO 2020-01-02  2020/01/02
1   vansh   23           23000   Hr 2023-01-01  2023/01/01
2   lalit   45           22000  CTO 2025-02-01  2025/02/01
3     Anu   33           23000   DA 2026-11-11  2026/11/11

In [59]:
df1['DOJ2'].dtype

dtype('O')

In [60]:
df1['DOJ2']=pd.to_datetime(df1['DOJ2'],format='%Y/%m/%d')

In [61]:
df1['DOJ2'].dtype

dtype('<M8[ns]')

In [62]:
df = df.drop('DOJ2',axis=1)
df

     name  Age  Monthly_salary team        DOJ
0  madhav   19           35000  CEO 2020-01-02
1   vansh   23           23000   Hr 2023-01-01
2   lalit   45           22000  CTO 2025-02-01
3     Anu   33           23000   DA 2026-11-11

In [63]:
# extract year,month,week,day
df['DOJ'].dt.year

0    2020
1    2023
2    2025
3    2026
Name: DOJ, dtype: int32

In [64]:
df['DOJ'].dt.month

0     1
1     1
2     2
3    11
Name: DOJ, dtype: int32

In [65]:
df['DOJ'].dt.day

0     2
1     1
2     1
3    11
Name: DOJ, dtype: int32

In [66]:
df['DOJ'].dt.day_name()

0     Thursday
1       Sunday
2     Saturday
3    Wednesday
Name: DOJ, dtype: object

In [67]:
df['Month'] =df['DOJ'].dt.month

In [68]:
df

     name  Age  Monthly_salary team        DOJ  Month
0  madhav   19           35000  CEO 2020-01-02      1
1   vansh   23           23000   Hr 2023-01-01      1
2   lalit   45           22000  CTO 2025-02-01      2
3     Anu   33           23000   DA 2026-11-11     11

In [69]:
#df['DOJ'] + pd.Timedelta(days=90)

In [70]:
# 8. Handling missing values
df

     name  Age  Monthly_salary team        DOJ  Month
0  madhav   19           35000  CEO 2020-01-02      1
1   vansh   23           23000   Hr 2023-01-01      1
2   lalit   45           22000  CTO 2025-02-01      2
3     Anu   33           23000   DA 2026-11-11     11

In [71]:
df.isnull()

    name    Age  Monthly_salary   team    DOJ  Month
0  False  False           False  False  False  False
1  False  False           False  False  False  False
2  False  False           False  False  False  False
3  False  False           False  False  False  False

In [72]:
import numpy as np
df.loc[df.name=='Anu','Monthly_salary'] = np.nan

In [73]:
df

     name  Age  Monthly_salary team        DOJ  Month
0  madhav   19         35000.0  CEO 2020-01-02      1
1   vansh   23         23000.0   Hr 2023-01-01      1
2   lalit   45         22000.0  CTO 2025-02-01      2
3     Anu   33             NaN   DA 2026-11-11     11

In [74]:
df.isnull()

    name    Age  Monthly_salary   team    DOJ  Month
0  False  False           False  False  False  False
1  False  False           False  False  False  False
2  False  False           False  False  False  False
3  False  False            True  False  False  False

In [75]:
df.isnull().sum()

name              0
Age               0
Monthly_salary    1
team              0
DOJ               0
Month             0
dtype: int64

In [76]:
df.fillna(0)

     name  Age  Monthly_salary team        DOJ  Month
0  madhav   19         35000.0  CEO 2020-01-02      1
1   vansh   23         23000.0   Hr 2023-01-01      1
2   lalit   45         22000.0  CTO 2025-02-01      2
3     Anu   33             0.0   DA 2026-11-11     11

In [77]:
# 9. Aggregation & group By

In [78]:
df['team'].value_counts() # frequency of value

team
CEO    1
Hr     1
CTO    1
DA     1
Name: count, dtype: int64

In [79]:
df['Month'].value_counts()

Month
1     2
2     1
11    1
Name: count, dtype: int64

In [80]:
df[df['Month']==1].value_counts

<bound method DataFrame.value_counts of      name  Age  Monthly_salary team        DOJ  Month
0  madhav   19         35000.0  CEO 2020-01-02      1
1   vansh   23         23000.0   Hr 2023-01-01      1>

In [81]:
df.groupby('Month')['Monthly_salary'].sum() # aggregation based on groupnby

Month
1     58000.0
2     22000.0
11        0.0
Name: Monthly_salary, dtype: float64

In [82]:
df.groupby('Month').agg({'Monthly_salary':'mean','name':'count'})

       Monthly_salary  name
Month
1             29000.0     2
2             22000.0     1
11                NaN     1

In [84]:
# 10.Concatenate and Merge Dataframe (Joins)

In [85]:
df1 = pd.DataFrame({'ID':[1,2,3,4],'Name':['A','B','C','D']})
df1

   ID Name
0   1    A
1   2    B
2   3    C
3   4    D

In [86]:
df2 = pd.DataFrame({'ID':[1,2,3,4],'Score':[88,98,76,94]})
df2

   ID  Score
0   1     88
1   2     98
2   3     76
3   4     94

In [90]:
pd.concat([df1,df2],axis=0) # vertical / row level / top on

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
3   4    D    NaN
0   1  NaN   88.0
1   2  NaN   98.0
2   3  NaN   76.0
3   4  NaN   94.0

In [92]:
pd.concat([df1,df2],axis=1) # horizantal / column level / side on side

   ID Name  ID  Score
0   1    A   1     88
1   2    B   2     98
2   3    C   3     76
3   4    D   4     94

In [93]:
# Merge = join
pd.merge(df1,df2,how = 'inner',on = 'ID')

   ID Name  Score
0   1    A     88
1   2    B     98
2   3    C     76
3   4    D     94

In [94]:
pd.merge(df1,df2,how = 'left',on = 'ID')

   ID Name  Score
0   1    A     88
1   2    B     98
2   3    C     76
3   4    D     94

In [95]:
pd.merge(df1,df2,how = 'right',on = 'ID')

   ID Name  Score
0   1    A     88
1   2    B     98
2   3    C     76
3   4    D     94

In [96]:
pd.merge(df1,df2,how = 'outer',on = 'ID')

   ID Name  Score
0   1    A     88
1   2    B     98
2   3    C     76
3   4    D     94

In [97]:
pd.merge(df1,df2,how = 'inner',left_on = 'ID',right_on='ID')

   ID Name  Score
0   1    A     88
1   2    B     98
2   3    C     76
3   4    D     94

In [98]:
# 11.AI /Chatgpt

In [99]:
df

     name  Age  Monthly_salary team        DOJ  Month
0  madhav   19         35000.0  CEO 2020-01-02      1
1   vansh   23         23000.0   Hr 2023-01-01      1
2   lalit   45         22000.0  CTO 2025-02-01      2
3     Anu   33             NaN   DA 2026-11-11     11

In [100]:
# filter salary > 20000 and january employees
df[(df['Month'] == 1)&(df['Monthly_salary']>=20000)]

     name  Age  Monthly_salary team        DOJ  Month
0  madhav   19         35000.0  CEO 2020-01-02      1
1   vansh   23         23000.0   Hr 2023-01-01      1

In [102]:
df.query("Month ==1 and Monthly_salary >= 25000") # query methjod

     name  Age  Monthly_salary team        DOJ  Month
0  madhav   19         35000.0  CEO 2020-01-02      1